[package]
name = "personachain_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "personachain_core"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7"
